### ISSUE TITLE
Very slow KNX status updates

### ISSUE THREAD

**Issue by resoai** [open-homeautomation/pknx#16]
I'm sorry to trouble you here however  it looks like I'm not getting any  response at homeassistant. 

After recent rewrite to async KNX switches take between 12 and 25 seconds to update it's values when switching lights off. Very strange thing is that switching lights on updates very fast both via hass and via physical buttons. The actual command gets executed momentarily i.e. turn on/off without delay. I have only started experiencing it since 0.32.

**Comment by keerts** [comment]
Same observation here. When I use the ETS group monitor, I see that it takes untill the next GroupValueRead to come by until the action takes place. I glanced over the code, but couldn't find out why there could be a difference between the On and Off actions. I hope to find time to debug this.

**Comment by keerts** [comment]
I also tried `cache: False`, as the code seems to use the value of that configuration parameter. When set to False other Exceptions pop up. This needs further investigation which I am willing to put up, just need to find some time.

**Comment by keerts** [comment]
Other than that and before we forget... this is a great module, I am having a lot of fun with it in home-assistant.

**Comment by resoai** [comment]
If only I could help in some way besides testing... Really looking forward to fixing this finally.

**Comment by keerts** [comment]
I will get back to you when I have had some time to debug.

**Comment by keerts** [comment]
I have done some debugging today and the problem is not in knxip. I was able to fix it by changing the following line in the knx.py file in home-assistant (line 140):

`self.update_ha_state()` --> `self.update_ha_state(True)`

I have not looked into the ha code why exactly this resolves the problem. When I find out, I will create a pull request for it. For now, change it manually and restart hass.

@resoai can you confirm this works for you as well?

**Comment by resoai** [comment]
@keerts thanks so much! I can confirm that it solves the problem.
